### ISSUE TITLE
Bug - Reset M5Stack

### ISSUE THREAD

**Issue by jbkim** [curdeveryday/vscode-m5stack-mpy#1]
I've tested this extension and found the "Reset M5Stack" command is not working.

**Comment by curdeveryday** [comment]
Which platform are you using?

**Comment by jbkim** [comment]
macOS. Is it ok for Windows OS ?

**Comment by curdeveryday** [comment]
Yep, I test on my windows and linux, it works. I will have a try on macOS later.

**Comment by curdeveryday** [comment]
I have checked the problem, it is possibly caused by a loop in your code like white True:, which will prevent you run the code or reset your device. So I suggest that you can use codes below to solve it:
```python
while True:
    #  Here is your code
    wait_ms(1)
```
