### ISSUE TITLE
Add M5Stack button not displaying

### ISSUE THREAD

**Issue by mikloskolovics** [curdeveryday/vscode-m5stack-mpy#12]
Hi!

I have opened this issue as I saw that others had issues with the button, just as I have now. Details of my setup:

VS Code:
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

Extension:
vscode-m5stack-mpy v1.0.11

UIFlow 1.8.2 USB mode

**Comment by robinkam** [comment]
This issue has been fixed on the latest version 1.0.13. Please update the extension in the VS Code. 
I reported the issue to the contributor directly and provided the error message in the VS Code Dev Tools. He fixed the issue right away. Thanks a lot!

**Comment by mikloskolovics** [comment]
I can confirm that, after updating the module, the button appeared for me, as well. Thanks!
