### ISSUE TITLE
extension revamping

### ISSUE THREAD

**Issue by darul75** [curdeveryday/vscode-m5stack-mpy#15]
Hello @curdeveryday,

First of all thanks a lot for having done all of this work for us, very useful.

If you want I am about rewriting it from scratch keeping the same logic/features, so I will start by a fork and then do a proposal through a PR later.

I have been playing quite a lot with the extension, debugging it, making changes there and there on how the serial communication was done etc...

My main question is around the following:

- where did you get a chance to find any informations about the CRC code that you are using https://github.com/curdeveryday/vscode-m5stack-mpy/blob/master/src/serialport.js#L56 are you working for m5stack and would you be able to share this information with me. I am also a bit confused by the crc_table..
- then same applies for the command codes https://github.com/curdeveryday/vscode-m5stack-mpy/blob/master/src/serialport.js#L23 have you like reverse engineered the UIFlow application to get this information

I got other questions but will raise them later.

**Comment by curdeveryday** [comment]
Hi @darul75 ,

Thank you for your development. As you guessed, I work for M5Stack. About the CRC and command code, they were provided to me by my embedded colleague. You can understand it as the communication protocol of UIFlow USB Mode. We did not open source UIFlow, so users can’t find this part of the information in our docs.

**Comment by darul75** [comment]
Hi @curdeveryday 

Thank you for your reply, I have been busy with this stuff but I have made some good progress I think and the result could potentially nice for you product.

One thing I noticed that would be useful to know and if you could ask internally at M5Stack is about uploading binary files like images. Each time I try to upload a file of that type, like a PNG image, I always got the following crc error code `crc error2k`, I am not going to put here the content of the Buffer but I could :)

Is there something that could/should be passed when uploading a binary content like in this Buffer

Example given with overriding:

```code
const buffer = Buffer.concat([
      Buffer.from([0x06]),
      Buffer.from(filename),
      Buffer.from([0x00]),
      Buffer.from([0x01]),
      data,
    ]);
```

I have tried to split the buffer in multiple chunks/sending them, all kind of things but it never works.

Here is just to give you an overview of the codebase.

https://github.com/darul75/vscode-m5stack-mpy/tree/master/src

And then a small screenshot for teasing.

<img width="342" alt="Screenshot 2021-11-18 at 20 28 32" src="https://user-images.githubusercontent.com/2134003/142483904-be68a2b1-634f-44e8-ae1e-fc850ce9090e.png">

Please help that would be nice, and then at some point we can align, jump on a call also if you wish.

There is still a lot of room for improvement and I will continuing cleaning the code.

Welcome to Typescript!

**Comment by darul75** [comment]
At the moment I got:

- Devices detection
- Tree buidling
- Refresh
- Create/Delete/Save file

Need to finish implementing Run...and other things to be migrated in TS but so far interesting work.

**Comment by darul75** [comment]
all features should now be operational, had some issues at the beginning to use the usbport package dependency, will try putting it back before raising this big PR

**Comment by darul75** [comment]
PR merged.
