### ISSUE TITLE
no add m5stack icon available in recent upgrade

### ISSUE THREAD

**Issue by machinehistories** [curdeveryday/vscode-m5stack-mpy#5]
After upgrading I no longer have an m5stack button to connect to the device. I do have have 3 commands available in the command palette reset, run, and explorer
![image](https://user-images.githubusercontent.com/26831444/76723417-6decff80-6704-11ea-93f9-42a28837999e.png)

**Comment by chaoranxie** [comment]
having the same issue

**Comment by chaoranxie** [comment]
just found something interesting, it looks like the extension works(showing Add M5Stack Button) when I plugin a M5Stack Core but not M5Stick C. 

@machinehistories if you are still struggling with accessing file system on M5Stack device, try using `ampy` and `mpfshell`, I am able to `get` and `put` data with those.

**Comment by machinehistories** [comment]
Thanks for that tip. I find upycraft is a good way to manage files on the
m5 boards as well as ampy. It gives you a gui and you can do some drag and
drop file management.

**Comment by wmedsantos** [comment]
I have the same problem. Can't add my Stick-C to VSCode. I'm using Mac Mojave.

**Comment by JoepSchyns** [comment]
Same issue here on macOS. I **downgraded** to **1.0.3** and that solved the issue.

**Comment by Hundhu-lab** [comment]
I use the 1.0.5 and I lost the "add M5Stick"-Button too. 
Downgrading to 1.0.4 or 1.0.3 dosn´t fix it.
On the Explorer ther is the empty filsystem only.

**Comment by Hundhu-lab** [comment]
I uninstalled and reinstalled it.
Now I have the arrow "run in M5Stacke". But not the rest. When I press the arrow, I get the error message "command 'treeview.item.run' not found"

**Comment by csadams** [comment]
Same issue... VSCode doesn't show the button to connect to my M5StickC
I'm running Windows 10,  VSCode 1.49.0 and vscode-m5stack-mpy extension ver 1.0.5,  My M5StickC has 1.6.3 on board.  It connects fine with M5Burner and M5Flow (UI Flow IDE), though the latter one keeps asking me to install the driver, even though I've done so 5 times now. 
Looks like this has been an issue for 6+ months, but no response from the developers?

**Comment by momoba2003** [comment]
I have the same problem. I'm using VSCode 1.49.0 on macOS Catalina.

**Comment by wataruland** [comment]
Although it is not a solution and waiting for an update, in order to continue using it I have downloaded / installed the portable version of VSCode 1.48.2 and from this version I have installed vscode-m5stack-mpy. Now I have two VSCode, one for arduino and Python and one for M5Stack Core.

**Comment by curdeveryday** [comment]
Update to lastest vscode (v1.49.x) and extension (v1.0.6).

**Comment by momoba2003** [comment]
I updated to the lastest vscode(v1.49.0 and vscode-m5stack-mpy(v1.0.6), however the problem is still here. So sad！

**Comment by Hundhu-lab** [comment]
I used the v.1.49.0 too. But the latest is the 1.49.1 at the moment. It works with the latest version.
