### ISSUE TITLE
Add M5Stack button not displaying

### ISSUE THREAD

**Issue by alcastle** [curdeveryday/vscode-m5stack-mpy#6]
OS: Ubuntu 20.04
VSCode: 1.49.1
Plugin: vscode-m5stack-mpy version 1.0.6

Plugin installs without complaint, asks to reload/restart VSCode.

The "Add M5Stack" button that should display does not. I don't see another way of using this plugin without the button.

**Comment by nexus166** [comment]
same here, trying to add an M5StickC running UIFlow 1.6.3

**Comment by rdlaner** [comment]
Same issue here. Ideally there would be a way to "Add M5Stack" through the command palette. As it is, I'm unable to use the extension.

**Comment by dcmcshan** [comment]
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

v1.0.6

Same issue!  No button with M5Stack Core.

**Comment by koh523** [comment]
Same issue. No "Add M5Stack" button appears.

- VSC
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0 / MAC OS 10.15.6

- Extension
vscode-m5stack-mpy: 1.0.6

**Comment by pa-at** [comment]
Same issue: No "Add M5Stack" button appears so that the extension is completely useless.

OS: Windows 10, 2004
VSCode: 1.5.01
Extension: vscode-m5stack-mpy 1.0.6

**Comment by mpatafio** [comment]
I've resolved using 

Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z (4 mos ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.3.0

extension: vscode-m5stack-mpy v1.0.7

**Comment by mhfalken** [comment]
On window the following combination works:

VSCODE:
Version 1.52.1 (November)
(Version 1.53 (January 2021 does NOT work))

Extension:
vscode-m5stack-mpy v1.0.7

So install the above version and disable auto update: File > Preferences > Settings: Update:Mode None.

**Comment by jarl-dk** [comment]
Same here for
OS: Ubuntu 20.04
VSCode: 1.53.2
Plugin: vscode-m5stack-mpy version 1.0.7

**Comment by pitor** [comment]
Same her. No button is displayed. Please fix it M5Stack.

OS: MacOS Big Sur
VSCode: 1.53.2
Plugin: vscode-m5stack-mpy version 1.0.7

**Comment by jarl-dk** [comment]
@curdeveryday : Could you please verify the fix for the new VSCode and the merge the PR and release a new version if everything is OK?

**Comment by mhfalken** [comment]
I can confirm that the fix 1.0.8 works with the newest version of VSC 1.53.2 in Windows.

**Comment by jarl-dk** [comment]
I also confirm that version 1.0.8 works with the latest stable release of VSC.

**Comment by windoze** [comment]
OS: Mac 11.3.1
VSCode: 1.56.0
Plugin: vscode-m5stack-mpy version 1.0.9
UIFlow: 1.7.6
Device: M5Stack Core 2

Cannot see the "Add M5Stack Device" button on the status bar

**Comment by mhfalken** [comment]
It work fine on Window (1.56.2), but I am also using the latest plugin, version 1.0.11.

**Comment by jarl-dk** [comment]
Works fine on Linux as well with latest vscode 1.56.2 and plugin 1.0.11

**Comment by jarl-dk** [comment]
@curdeveryday: Isuggest you close this bug as resolved.

**Comment by windoze** [comment]
It works now on VSCode 1.56.2 with plugin version 1.0.11, thanks!

**Comment by michaelkhuber** [comment]
Does not work for me with VSCode 1.65 and plugin version 1.1.4

**Comment by KafCoppelia** [comment]
Does not work for me with VSCode 1.69 and plugin version 1.1.7 on Archlinux 5.18.14

**Comment by steve-bate** [comment]
Doesn't work for me on macOS 12.5, VS Code 1.69.2, and plugin version 1.1.7. Should we open a new issue for this?

**Comment by urishev55** [comment]
Add M5Stack button not displaying
vscode x64-1.74.1

**Comment by mike65535** [comment]
Problem still exists. Running Linux here. On one PC, the "Add M5Stack" option appears, on the other PC it does not.
VScode 1.74.2
vscode-m5stack-mpy 1.1.9
I

**Comment by blog2i2j** [comment]
add button not displaying too.
vscode x64-1.84.2-windows
vscode-m5stack-mpy 1.1.10
windows 11

**Comment by irvsys** [comment]
Same for me:
add button not displaying too.
vscode x64-1.84.2-windows
vscode-m5stack-mpy 1.1.10
windows 10

No "add M5 Stack" button at bottom left of UI.
Tried multiple uninstall / re-install of the plugin, but no button shows.

**Comment by Mauker1** [comment]
Same issue here.

vscode 1.85.1
plugin 1.1.10
Win 11

There is no button whatsoever. I tried downgrading to a couple of different versions with no luck.

**Comment by kinoshita-lab** [comment]
Hi, I found the solution for this issue if your problem derives from same reason. 
Please refer to: https://github.com/curdeveryday/vscode-m5stack-mpy/issues/13#issuecomment-1895764675

Hope it works..

**Comment by Mauker1** [comment]
> Hi, I found the solution for this issue if your problem derives from same reason. Please refer to: [#13 (comment)](https://github.com/curdeveryday/vscode-m5stack-mpy/issues/13#issuecomment-1895764675)
> 
> Hope it works..

I can confirm that this solves my issue with the latest version (1.1.10) Thank you!

**Comment by chernogorsky** [comment]
Mac M1, vs 1.94.2 m5stack 1.1.10 - no button/sign of the installed and enabled plugin.
Fixed by
cd ~/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.1.10
npm rebuild @serialport/bindings
